# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: get-cmake
        uses: lukka/get-cmake@v3.19.2  
      
      - name: run-cmake
        uses: lukka/run-cmake@v3.2
        id: cmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeSettingsJson'
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/out/build/'
      
      - name: List files
        run: ls
      
      - name: List files
        run: ls '${{ runner.workspace }}/out/build/x64-Debug/dev_test'
      
      - name: Run
        run: '${{ runner.workspace }}/out/build/x64-Debug/dev_test/main.exe'
  build_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: get-cmake
        uses: lukka/get-cmake@v3.19.2  
      
      - name: run-cmake
        uses: lukka/run-cmake@v3.2
        id: cmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeSettingsJson'
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/out/build/'
      
      - name: List files
        run: ls
      
      - name: List files
        run: ls '${{ runner.workspace }}/out/build/x64-Debug/dev_test'
      
      - name: Run
        run: '${{ runner.workspace }}/out/build/x64-Debug/dev_test/main'
