name: CI


on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: get-cmake
        uses: lukka/get-cmake@v3.19.2  
      
      - name: run-vcpkg
        uses: lukka/run-vcpkg@v6.0
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg_manifest/vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}

      - name: run-cmake
        uses: lukka/run-cmake@v3.2
        id: cmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeSettingsJson'
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/out/build/'
          useVcpkgToolchainFile: true
          buildWithCMake: true
      
      - name: List files
        run: ls
      
      - name: List files
        run: ls '${{ runner.workspace }}/out/build/x64-Debug/dev_test'
      
      - name: Run
        run: '${{ runner.workspace }}/out/build/x64-Debug/dev_test/main.exe'
        
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: get-cmake
        uses: lukka/get-cmake@v3.19.2  
      
      - name: run-vcpkg
        uses: lukka/run-vcpkg@v6.0
        with:
         setupOnly: true
         vcpkgDirectory: '${{ github.workspace }}/vcpkg'
         appendedCacheKey: ${{ hashFiles( '**/vcpkg_manifest/vcpkg.json' ) }}
         vcpkgTriplet: ${{ matrix.triplet }}
      
      - name: run-cmake
        uses: lukka/run-cmake@v3.2
        id: cmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeSettingsJson'
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/out/build/'
          useVcpkgToolchainFile: true
          buildWithCMake: true
      
      - name: List files
        run: ls
      
      - name: List files
        run: ls '${{ runner.workspace }}/out/build/x64-Debug/dev_test'
      
      - name: Run
        run: '${{ runner.workspace }}/out/build/x64-Debug/dev_test/main'
